alanguage: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
install:
  - nvm install 10
  - nvm use 10
  - npm ci
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master